### ISSUE TITLE
dbus auth protocol compatiblity issues

### ISSUE THREAD

**Issue by jcbinf** [cocagne/txdbus#33]
I am running on a centos 5 system and python 2.6.8 (python26) and dbus authentication does not work smoothly.  In particular mechanism EXTERNAL never succeeds.  It appears the root cause is the client and server not being in sync early in the auth sequence, and EXTERNAL being first in the order gets discarded.

After brief investigation it appears the ClientAuthenticator implementation might not be ideal.  It might benefit from sending an empty AUTH which should give a server response listing mechanisms, and get client and server in sync right away.

The dbus server on this centos 5 system rejects the first auth attempt from txdbus which by default tries EXTERNAL.  Seeing errors returned like "Not currently in an auth conversation" is a key diagnostic.

I got it to work by adding a  second EXTERNAL after the first in the 'preference' member variable.  Not a preferred solution, but it is diagnostic.

**Comment by cocagne** [comment]
I just double-checked the DBus specification and pre-authentication
synchronization is not required. It sounds like the dbus daemon included in
Centos 5 is buggy in that regard. It's good to know you found a workaround
and were able to get up and running but I'm not sure it makes sense to
modify the txdbus implementation to support a buggy daemon on an
out-of-date platform. It could be done, of course, possibly as an optional
"centos5_auth_bug_workaround=True" flag on the connect method but I'd need
some convincing that this is a good idea.

Tom

**Comment by hobarrera** [comment]
Okay to close this?

**Comment by cocagne** [comment]
Yup. Thanks.
