### ISSUE TITLE
Export simple object with integer as an argument.

### ISSUE THREAD

**Issue by LaPriWa** [cocagne/txdbus#38]
I want to become familiar with **txdbus**, which is a native **dbus** implementation that uses **twisted**. I want to export an simple object in order to remotely call its only method with **python 2.7**. The example given at http://pythonhosted.org/txdbus/ works properly.

I changed the example_method a little bit. Now it takes an integer, instead of a string, like the original example method does. I took this into account when specifying the interface. 

**Server:**

    from twisted.internet import reactor, defer
    from txdbus           import client, objects, error
    from txdbus.interface import DBusInterface, Method
    import time
    
    class MyObj (objects.DBusObject):
    
        iface = DBusInterface('org.example.MyIFace',
                              Method('exampleMethod', arguments='i', returns='s'))
    
        dbusInterfaces = [iface]
    
        def __init__(self, objectPath):
            super(MyObj, self).__init__(objectPath)
    
    
        def dbus_exampleMethod(self, arg):
            time.sleep(arg)
            return 'success'
    
    
    @defer.inlineCallbacks
    def main():
        try:
            conn = yield client.connect(reactor)
    
            conn.exportObject( MyObj('/MyObjPath') )
    
            yield conn.requestBusName('org.example')
    
            print 'Object exported on bus name "org.example" with path /MyObjPath'
    
        except error.DBusException, e:
            print 'Failed to export object: ', e
            reactor.stop()
    
    
    reactor.callWhenRunning( main )
    reactor.run()

The client calls the example method exactly as in the original example client but with an integer instead of a string.

**Client:**

    from twisted.internet import reactor, defer
    from txdbus import client, error
    
    
    @defer.inlineCallbacks
    def main():
    
        try:
            cli   = yield client.connect(reactor)
    
            robj  = yield cli.getRemoteObject( 'org.example', '/MyObjPath' )
    
            reply = yield robj.callRemote('exampleMethod', 2)
    
            print 'Reply from server: ', reply
    
        except error.DBusException, e:
            print 'DBus Error:', e
    
        reactor.stop()
    
    
    reactor.callWhenRunning(main)
    reactor.run()

Executing both the server and the client yields the error message:
    
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1184, in gotResult
        _inlineCallbacks(r, g, deferred)
      File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
        result = g.send(result)
      File "tx_example_client.py", line 16, in main
        reply = yield robj.callRemote('exampleMethod', 'Hello World!')
      File "/usr/local/lib/python2.7/dist-packages/txdbus/objects.py", line 284, in callRemote
        returnSignature  = m.sigOut )
    --- <exception caught here> ---
      File "/usr/local/lib/python2.7/dist-packages/txdbus/client.py", line 519, in callRemote
        autoStart    = autoStart )
      File "/usr/local/lib/python2.7/dist-packages/txdbus/message.py", line 190, in __init__
        self._marshal()
      File "/usr/local/lib/python2.7/dist-packages/txdbus/message.py", line 103, in _marshal
        binBody = b''.join( marshal.marshal( self.signature, self.body )[1] )
      File "/usr/local/lib/python2.7/dist-packages/txdbus/marshal.py", line 612, in marshal
        nbytes, vchunks = marshallers[ tcode ]( ct, var, startByte, lendian )
      File "/usr/local/lib/python2.7/dist-packages/txdbus/marshal.py", line 405, in marshal_int32
        return 4, [ struct.pack( lendian and '<i' or '>i', var) ]
    struct.error: cannot convert argument to integer

What am I doing wrong? It would be great if someone could help me with this issue. It would be the coolest, if someone could explain to me what the error means.

**Comment by cocagne** [comment]
My best guess is that you forgot to save the client file before executing.
If you notice from the stack trace, you're calling the method with the
string "Hello World!" instead of the integer 2:

File "tx_example_client.py", line 16, in main
    reply = yield *robj.callRemote('exampleMethod', 'Hello World!')*


Tom

**Comment by LaPriWa** [comment]
You are absolutely right. What a stupid mistake. Thank you very much for your kind help!

**Comment by cocagne** [comment]
Heh, no problem. That kind of thing happens all the time.
