### ISSUE TITLE
publishing an Object on a session-bus

### ISSUE THREAD

**Issue by LaPriWa** [cocagne/txdbus#41]
I wrote two scripts which publish one object each on a session-bus with bus name "de.test.objectbus".
When I execute one of the scripts the objects are perfectly published and I can execute all of the remote methods specified by the interfaces. The interfaces have different names and the object have different object-paths.

My question: Is it possible to publish an remote object on a session-bus which has already been created with the reactor running? Or do I have to publish all objects on that bus before I start the reactor?

**Comment by cocagne** [comment]
The Twisted reactor should be running before you do anything with txdbus.
