### ISSUE TITLE
Native test (ocasionally) fails

### ISSUE THREAD

**Issue by hobarrera** [cocagne/txdbus#52]
This is kinda hard to reproduce, since this test only fails **sometimes** (I'm guessing race condition or something alike).

It's `txdbus.test.test_client_against_native_bus.SignalTester.test_shared_signal`.

The easiest way to reproduce is running `trial -u txdbus`, which will run all tests in a loop, forever, until failure (it eventually fails).

**Comment by exvito** [comment]
Investigated this a little bit. Here's my take.

When the test fails, the result I get is:
```
txdbus.test.test_client_against_native_bus
  SignalTester
    test_shared_signal ...                                              [ERROR]

===============================================================================
[ERROR]
Traceback (most recent call last):
Failure: twisted.internet.error.ConnectionDone: Connection was closed cleanly.

txdbus.test.test_client_against_native_bus.SignalTester.test_shared_signal
-------------------------------------------------------------------------------
Ran 1 tests in 0.016s

FAILED (errors=1)
```


Test code is:

```
    def test_shared_signal(self):

        d1 = defer.Deferred()
        d2 = defer.Deferred()

        def on_proxy( ro ):
            ro.notifyOnSignal('sharedSignal', d1.callback,
                              interface='org.txdbus.trial.Signal')
            ro.notifyOnSignal('sharedSignal', d2.callback,
                              interface='org.txdbus.trial.Signal2')

            ro.callRemote('sendShared1')
            ro.callRemote('sendShared2')


        self.get_proxy().addCallback(on_proxy)


        dl = defer.DeferredList( [d1,d2] )

        def check_result( result ):
            self.assertEquals( result[0], (True, 'iface1') )
            self.assertEquals( result[1], (True, 'iface2') )

        dl.addCallback(check_result)

        return dl
```

My reasoning:
* This test is issuing two unsyncronized `callRemote`s.
* Suspicion:
  * Test ends -- meaning the `check_result` callback being called.
  * One of the outgoing connections associated to a `callRemote` is still up.

What I did:
* Instrumented the test by adding callbacks to each individual `callRemote`.
* Such callbacks just print out 'callRemote complete' and return the result they received.

After that I went back to `trial -u ...`. It ran for a while and when it failed my suspicion was confirmed -- I had two 'callRemote complete' output lines for every successful test run, but only a single one on the failed test run.

The solution involves forcing the test completion to wait for both `callRemotes` to complete. Maybe appending both their returned deferreds to the deferred list being returned by the test is enough.

My 2c.

**Comment by hobarrera** [comment]
From your analysis, I stared at this method during enough time to literally dream about it, but failed to see that. 😆
