### ISSUE TITLE
Test test_get_all_properties fails with given PYTHONHASHSEED

### ISSUE THREAD

**Issue by exvito** [cocagne/txdbus#54]
While exploring tox and testing in general, I found out that one particular test was failing unpredictably on my dev system, under Python 2.7.

I found a way of reproducing it by passing in a particular value for PYTHONHASHSEED.

I run the test with `trial  txdbus.test.test_client_against_native_bus.InterfaceTester.test_get_all_properties` which will only run if a DBUS session is up. So, on my dev VM with no GUI, I actually run `dbus-run-session trial  txdbus.test.test_client_against_native_bus.InterfaceTester.test_get_all_properties`. This runs successfully most of the time.

To force a failure, I need to set PYTHONHASHSEED to 3475844530 by running `PYTHONHASHSEED=3475844530 dbus-run-session trial  txdbus.test.test_client_against_native_bus.InterfaceTester.test_get_all_properties` which consistently fails for me.

Taking a quick peek at the test itself, in `txdbus/test/client_tests.py`...

```
    def test_get_all_properties(self):

        def got_object(ro):
            return ro.callRemote('GetAll', '')

        def got_reply(reply):
            self.assertEquals(reply, {'common'   : 'common1',
                                      'prop1'    : 'foobar',
                                      'prop2'    : 5,
                                      'prop_if1' : 'pif1',
                                      'pwrite'   : 'orig'})

        return self.proxy_chain(got_object, got_reply)
```

...it is calling the `GetAll` method with an empty interface argument. Not being familiar with DBUS specifics, the behavior seems to be returning a "merged" result of two interfaces in `TestClass` at around line 1388: these are `org.txdbus.trial.IFace1` and `org.txdbus.trial.IFace2`.

Given that both interfaces expose/declare a property named `common`, respectively supported by the `common1` and `common2` attributes in the class, it seems that for most cases of the test run, `common1`'s value is returned, but for the particular PYTHONHASHSEED mentioned above, `common2`'s value is returned and the test fails.

Questions on my mind at that point:
1. First things first: what's the specification for the behaviour of `GetAll` when an empty interface argument is passed in? Is it supposed to merge/combine the existing interfaces? If so how?
2. If `GetAll` should return a merged/combined list of all existing interfaces, and assuming that somehow order is important when facing overlapping names, then the current implementation needs fixing.
3. If, otherwise, no such speficification for `GetAll` exists -- and, say, the result may be arbitrary (again, I have no idea) --  then the test may need to be adapted to account for that possibility.

Then I skimmed through https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces-properties which apparently states that:

> An empty string may be provided for the interface name; in this case, if there are multiple properties on an object with the same name, the results are undefined (picking one by according to an arbitrary deterministic rule, or returning an error, are the reasonable possibilities).

So, it seems 3. above is the case -- unless txdbus wants to be stricter in this scenario, of course. :)

**Comment by exvito** [comment]
Note: I also got it to fail consistently under a quick-hack Python 3 almost 100% compatible branch (https://github.com/exvito/txdbus/tree/fd-support-py3) -- of course, with a different value for PYTHONHASHSEED of 1643278873.

**Comment by exvito** [comment]
More:

Given that https://pythonhosted.org/txdbus/dbus_overview.html states, for the `org.freedesktop.DBus.Properties.Get` method that...

> The interface name may be '', in which case, the implementation will use the first interface it finds that supports a property with the given name.

...I'd argue, for the sake of consistency, that 3. above is effectively the case -- that txdbus will not be stricter than that -- and that, thus, fixing this involves fixing the test to accomodate for the possible outcomes.

Feedback?

**Comment by hobarrera** [comment]
> The interface name may be '', in which case, the implementation will use the first interface it finds that supports a property with the given name.

I'd argue that this is a rephrase of the spec which is a bit unclear: the first one found **is** returned, but which one is found first is completely arbitrary ("undefined").

I agree with you that the test needs to account for this possibility, also also the docs should be slightly rephrased.

**Comment by cocagne** [comment]
Nice catch @exvito, I completely missed that. The simple solution is
probably just to check for either of the two results and declare success in
each case.
