### ISSUE TITLE
Skip tests.test_marshal.SigFromPyTests.test_long on Python 3

### ISSUE THREAD

**Issue by exvito** [cocagne/txdbus#61]
This test is a no-op on Python 3. Passing is misleading, it should be skipped instead.

See https://github.com/cocagne/txdbus/issues/11#issuecomment-306437799 in #11.

**Comment by hobarrera** [comment]
Sort-of fixed by #70, [here](https://github.com/cocagne/txdbus/pull/70/files#diff-fca6afb72f1f330579ba27f8b769e65e).
