### ISSUE TITLE
Fix invalid name "pn" in txdbus/router.py:Rule.match

### ISSUE THREAD

**Issue by exvito** [cocagne/txdbus#62]
Identified in https://github.com/cocagne/txdbus/issues/11#issuecomment-306205821, this really looks like a typo of some-kind, ready to fail once the code is hit.

**Comment by hobarrera** [comment]
I haven't fixed it so far because I'm unsure what the intention of the code is there. Is this meant to be `pn`? Or `self.pn`?

Maybe @cocagne better understands this, since it's been as-is since it's initial commit.

**Comment by exvito** [comment]
Looked at this for a bit.

Sharing a few thoughts after a rough read of the spec -- in particular the "Match Rules" section -- and inspecting the code:
* `path_namespace` is, among others, a kind of argument to `org.freedesktop.DBus.AddMatch`.
* `AddMatch` allows clients to define/filter which broadcast messages they are willing to receive.
* Per the spec, regarding rules, using `path_namespace` in `AddMatch`: "Matches messages which are sent from or to an object for which the object path **is either the given value, or that value followed by one or more path components.**" -- this highlight is the revelvant part, continue reading.

About the code in `Rule.match`:
* Processes one argument `m` which is a DBus message.
* If it "matches" the rule it then the message is handled via `self.callback(m)`.
* It filters out matches in the `if`s preceding the callback.
* The particular code snippet in this issue is:

```
    def match(self, m):
        try:

            # ...excluded for clarity

            if hasattr(self, 'path_namespace'):
                if m.path is None or not m.path.startswith(pn):
                    return

            # ...excluded for clarity

            # if we get here, we have a match
            self.callback( m )
        except:
            log.err()
```

Drilling it down:
* The first `if hasattr` says "path_namespace is defined for this rule, then consider these conditions for filtering".
* The `if m.path is None` is enough to return/fiter, given that it could never match `path_namespace`, which, per the previous line, is defined.
* My guess is that the snippet this issue is targeting -- `m.path.startswith(pn)` -- is supposed to implement the **bold** quoted part of the spec, above.

If I'm reading this correctly, the correct snippet for that would be `m.path.startswith(self. path_namespace)`.

@cocagne, is this making any sense?

**Comment by hobarrera** [comment]
This looks right to me. I definitely started assuming the same thing while I read the above, even before I reached the end. :P

**Comment by cocagne** [comment]
That sounds right. I haven't looked at this code in years though so It's
been long enough now that the details are entirely lost to me. I wouldn't
be surprised if there were an undetected mistake here since I expect it's
not a code path that's executed frequently.

**Comment by exvito** [comment]
#74 merged, this issue is closed.
