### ISSUE TITLE
Add code linter to CI infrastructure

### ISSUE THREAD

**Issue by exvito** [cocagne/txdbus#63]
See #11 from https://github.com/cocagne/txdbus/issues/11#issuecomment-306205172 onwards.

I'd start with running a linter on CI but not failing on errors. From there, individual issues / PRs can be created and addressed with a somewhat narrow-focus (example: one issue fixes E111 indentation not a multiple of 4, etc.)

Once we get the "good enough" results (up to discussion?), then maybe linter failures could prevent PR merges.

Thoughts welcome.

**Comment by hobarrera** [comment]
#70 starts to address this. I'm currently working on the existing codebase to fix failing checks, so we can have a clean starting ground for new PRs.
