### ISSUE TITLE
Main example is not Py2/3 safe

### ISSUE THREAD

**Issue by oberstet** [cocagne/txdbus#68]
Split out from #11 

Looking at the [example](https://github.com/cocagne/txdbus#usage-example) on the frontpage, I'm a bit puzzled that none of the arguments there is using explicit `b'..'` or `u'...'`. So the arguments will be bytes on Py2 and unicode on Py3. Are the arguments auto-coerced under the hood?

Take

```python
    notifier = yield con.getRemoteObject('org.freedesktop.Notifications',
                                         '/org/freedesktop/Notifications')
```

Does `getRemoteObject` take bytes or strings? If the latter, then the example code should read:

```python
    notifier = yield con.getRemoteObject(u'org.freedesktop.Notifications',
                                         u'/org/freedesktop/Notifications')
```

This code then works on both Python 2 and 3.

**Comment by hobarrera** [comment]
The arguments are all `str` on both python versions. On python2, bytes and `str` are the same thing:

```
>>> b'hi' == str('hi')
True
```

On python3, they're strings. There's no `unicode` type in python3, just strings.

**Comment by oberstet** [comment]
No, this isn't true:

```pythoo
oberstet@thinkpad-t430s:~/scm/crossbario/autobahn-python$ python2
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> type('') == type(b'')
True
>>> type('') == type(u'')
False
>>> 
oberstet@thinkpad-t430s:~/scm/crossbario/autobahn-python$ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> type('') == type(b'')
True
>>> type('') == type(u'')
False
>>> 
```

**Comment by oberstet** [comment]
Or using your example:

```python
oberstet@thinkpad-t430s:~/scm/crossbario/autobahn-python$ python3
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> b'hi' == str('hi')
False
>>> 
```

**Comment by hobarrera** [comment]
You're confusing python versions.

In both python versions, the literals are of type `str`. That's what's expected.

Furthermore, the examples work as expected on all supported pythons.

**Comment by oberstet** [comment]
This is getting boring;)  Read what I wrote. I am talking about _literals_. Next, str in Py is a synonym for bytes, whereas in Py 3 it is unicode. Then you don't have tests that roundtrip between _different_ Python versions, and in fact, I expect those to fail. I will leave it at that, feel free to ignore me.

**Comment by hobarrera** [comment]
> whereas in Py 3 it is unicode

No, that's wrong, the `unicode` class does not exist in python3, there's no such thing. All strings are proper unicode strings, and there's no separate class, because all the mess made in python2 was avoided.

I'd love to see an example that fails, and work around that, but I **won't** add a fix without seen some way of reproducing a bug/crash.
