### ISSUE TITLE
is this repository still maintained?

### ISSUE THREAD

**Issue by goffi-contrib** [cocagne/txdbus#94]
Hello,

and first of all thanks for your work!

This repository has not seen any update for 2 years, is it still maintained? Do you have any plan to update it?

If not, could be nice to specify it in the README and/or archive the repos.

Thanks!

**Comment by cocagne** [comment]
Yes, it's still maintained. The repo is primarily available for bugfixes as txdbus is feature complete with no planned enhancements.
